configure.ac:  Fix cython3 and python module detection
The `cython3` package installs `/usr/bin/cython3`:

    $ ./autogen.sh && ./configure
    checking for cython... no
    configure: error: not found

The `ac_python_module.m4` macros fail to detect python3 modules
because `$PYTHON` hasn't been set, and it defaults to `python`:

    checking python module: google.protobuf.descriptor... Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named google.protobuf.descriptor
    no
    configure: error: failed to find required module google.protobuf.descriptor